version: "3"
x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/home/trybe
  stdin_open: true
  tty: true
services:
  api:
    <<: *app
    command: >
      bash -c "cd api && yarn && yarn typeorm migration:run && yarn dev"
    ports:
      - 3333:3333
    depends_on:
      - database
  client:
    <<: *app
    command: >
      bash -c "cd client && yarn && yarn start"
    ports:
      - 3000:3000
    depends_on:
      - api
  database:
    image: "postgres"
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
    driver: local
